# .streamlit/secrets.toml

#password = "streamlit123"
[passwords]
admin = "admin"
user1 = "user1"
user2 = "user2"
user3 = "user3"
user4 = "user4"
user5 = "user5"

[herokudatabase]
host = "ec2-52-30-67-143.eu-west-1.compute.amazonaws.com"
port = 5432
dbname = "dam6pd7tvevt30"
user = "ydxmsdjpouttjb"
password = "13372ad36a05fc7fe953397287ce6797e1d91f835d2332f3b60370aeb6efb73c"