# .streamlit/secrets.toml

#password = "streamlit123"
[passwords]
admin = "admin"
user1 = "user1"
user2 = "user2"
user3 = "user3"
user4 = "user4"
user5 = "user5"

[postgres]
host = "localhost"
port = 5432
dbname = "postgres"
user = "postgres"
password = "sqlmz_00"